import assert from "node:assert/strict";
import { createDocument, cloneDocument, StrokeElement } from "../src/document";
import { EditorSnapshots } from "../src/editor-history";
import { optimizeShape } from "../src/shapes";

const doc = createDocument("grid");
const snapshots = new EditorSnapshots();
const stroke: StrokeElement = { type: "stroke", id: "a", color: "#111111", size: 4, points: [{ x: 1, y: 1, pressure: .5 }] };
doc.pages[0].elements.push(stroke);
const first = snapshots.capture(doc);
doc.pages[0].elements.push({ ...stroke, id: "b" });
const second = snapshots.capture(doc);
assert.equal(first.pages[0].elements.length, 1);
assert.equal(second.pages[0].elements.length, 2);
assert.equal(first.pages[0].elements[0], second.pages[0].elements[0], "committed copies are reused without recopying their points");
assert.notEqual(first.pages[0].elements[0], stroke, "history never holds live elements");
snapshots.invalidate();
stroke.points[0].x = 99;
const third = snapshots.capture(doc);
assert.equal((first.pages[0].elements[0] as StrokeElement).points[0].x, 1);
assert.equal((third.pages[0].elements[0] as StrokeElement).points[0].x, 99);
const restored = cloneDocument(second);
(restored.pages[0].elements[0] as StrokeElement).points[0].x = 44;
assert.equal((second.pages[0].elements[0] as StrokeElement).points[0].x, 1, "undo restoration cannot mutate shared history");
const line = { ...stroke, points: Array.from({length: 50}, (_, i) => ({x: i * 4, y: Math.sin(i / 49 * Math.PI) * 5, pressure: .5})) };
assert.equal(optimizeShape(line, 0).kind, null);
assert.equal(optimizeShape(line, .05).kind, null);
assert.equal(optimizeShape(line, 1).kind, "line");
console.log("Editor snapshot isolation and shape sensitivity tests passed");
