import assert from "node:assert/strict";
import { createDocument, parseDocument, StrokeElement } from "../src/document";
import { applyReconstructions, decodeCtc, reconstructLine, restoreReconstructions, segmentInkLines } from "../src/htr-core";
import { constructGeometry } from "../src/geometry-tools";

const make = (id: string, x: number, y: number, height = 35): StrokeElement => ({ type: "stroke", id, color: "#111", size: 3, points: [{ x, y, pressure: .5 }, { x: x + 10, y: y + height, pressure: .7 }] });
const document = createDocument("grid"); const page = document.pages[0];
page.elements = [make("b", 60, 100), make("a", 20, 100), make("c", 20, 200), make("dot", 23, 90, 2)];
const original = structuredClone(page.elements);
const lines = segmentInkLines(page.elements as StrokeElement[]);
assert.equal(lines.length, 2); assert.equal(lines[0].strokes.length, 3, "detached dot joins first line");
const reconstructed = lines.map((line, i) => reconstructLine(page, line, ["Hallo", "Welt"][i]));
applyReconstructions(page, reconstructed); assert.equal(page.elements.length, 2);
const reload = parseDocument(JSON.parse(JSON.stringify(document)))!.document.pages[0];
assert.equal(restoreReconstructions(reload), 4); assert.deepEqual(reload.elements, original, "original order and coordinates survive save/reload");
assert.equal(restoreReconstructions(reload), 0, "restore idempotent");
assert.throws(() => reconstructLine(page, lines[0], "stale"), /geändert/);
const classes = [1, 1, 0, 1, 2, 2, 0]; const logits = classes.flatMap(c => [0, 1, 2].map(k => c === k ? 10 : -10));
assert.equal(decodeCtc(logits, [1, 7, 3], "ab"), "aab");
assert.throws(() => decodeCtc(logits, [1, 7, 4], "ab"), /Alphabet/);
const base = { x: 300, y: 400, length: 100, angle: 30, sweep: 360, edge: 0 as const };
const line = constructGeometry("set-square", base, "#111", 3);
assert.ok(Math.abs(Math.hypot(line.points[1].x - 300, line.points[1].y - 400) - 100) < 1e-9);
assert.ok(Math.abs(line.points[1].y - 450) < 1e-9);
const circle = constructGeometry("compass", base, "#111", 3);
assert.equal(circle.kind, "ellipse"); assert.equal(circle.points[1].x - circle.points[0].x, 200);
const arc = constructGeometry("compass", { ...base, sweep: 120 }, "#111", 3);
assert.equal(arc.closed, false);
for (const p of arc.points) assert.ok(Math.abs(Math.hypot(p.x - 300, p.y - 400) - 100) < 1e-8);
assert.throws(() => constructGeometry("compass", { ...base, length: NaN }, "#111", 3));
page.format = "square"; page.width = 1200; page.height = 1200;
assert.equal(parseDocument(JSON.parse(JSON.stringify(document)))!.document.pages[0].height, 1200);
console.log("Handwriting reconstruction and construction tests passed");
