import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {normalizeHandwritingV2,smoothOwnInk,HandwritingV2Options} from "../src/handwriting-v2";
import {StrokeElement,elementBounds} from "../src/document";
const options:HandwritingV2Options={height:48,strength:0,pageWidth:1200,pageHeight:1697,paper:"grid",closeLoops:false};
const stroke=(id:string,xy:number[][]):StrokeElement=>({type:"stroke",id,color:"#111",size:3,points:xy.map(([x,y],i)=>({x,y,pressure:.5,time:i*8}))});
const letters=[stroke("a",[[100,240],[105,280],[110,300]]),stroke("b",[[161,260],[166,300]])];
const out=normalizeHandwritingV2(letters,{...options,spacing:.8,startX:800,baseline:800,rowStep:72,lockRows:true});
assert.deepEqual(out.strokes.map(s=>s.points.map(p=>p.x)),letters.map(s=>s.points.map(p=>p.x)),"height-only correction never changes horizontal positions or spacing");
assert.equal(out.baseline,300);assert.equal(out.endX,166);
assert.equal(Math.max(...out.strokes.flatMap(s=>s.points.map(p=>p.y))),300);
assert.equal(Math.min(...out.strokes.flatMap(s=>s.points.map(p=>p.y))),252);
const edge=stroke("edge",[[1190,100],[1199,150]]);
assert.equal(elementBounds(normalizeHandwritingV2([edge],options).strokes[0]).minX,1190,"no automatic wrapping near page edge");
assert.throws(()=>normalizeHandwritingV2([stroke("top",[[40,1],[50,20]])],options),/Position/,"not enough height keeps original instead of relocating");
const long=stroke("jitter",Array.from({length:81},(_,i)=>[100+i*.35+(i===0||i===80 ? 0 : Math.sin(i*1.7)*1.4),180+i]));
const fixed=smoothOwnInk(long.points,1);
const error=(points:typeof fixed)=>points.reduce((sum,p)=>sum+Math.abs(p.x-(100+(p.y-180)*.35)),0)/points.length;
assert.ok(error(fixed)<error(long.points)*.35,"sustained slanted stems get much straighter");
assert.deepEqual(fixed[0],long.points[0]);assert.deepEqual(fixed.at(-1),long.points.at(-1),"diagonal direction stays the writer's");
assert.deepEqual(smoothOwnInk(long.points,0),long.points,"strength zero leaves geometry untouched");
const loop=stroke("loop",Array.from({length:97},(_,i)=>{const a=i*Math.PI*2/96;return [200+30*Math.cos(a),200+40*Math.sin(a)];}));
const curved=smoothOwnInk(loop.points,1);
assert.ok(curved.every((p,i)=>Math.hypot(p.x-loop.points[i].x,p.y-loop.points[i].y)<.7),"smooth ovals are not flattened into straight segments");
const main=readFileSync("src/main.ts","utf8");
assert.ok(!main.includes('"Wortabstand"')&&!main.includes('"Zeile halten"')&&!main.includes('"Buchstabenabstand"'),"removed layout controls must not remain in UI");
assert.ok(!main.includes("normalizeHandwritingWord("),"turning improvement off cannot activate the old repositioning fallback");
console.log("Height-only anchors, unchanged gaps, safe margins, stronger slanted-stem correction and curved ink tests passed");
